version: '3'
services:
  rv-backend:
    build: .
    ports:
      - ${PORT:-8081}:${PORT:-8081}
    environment:
      - PORT=${PORT:-8081}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - NODE_ENV=${NODE_ENV}
      - JWT_SECRET=${JWT_SECRET}

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
